### PR TITLE
Updated version

### PR DESCRIPTION
**Pull request by ramirezg**
Updated draft version following specs below:
## My Cloud.gov/18F Controls/ Your Controls Documentation 
Without being combined with the standards and certifications yamls the control yamls can be use to generate readable documentation w/ gitbook, etc... 
```yaml
# cloud.yaml
controls:
  - name: Cloud Foundry User Authentication and Authorization (UAA)
    narrative: This is a separate component that blahblahblah. It segments access by blahblahblah.
    references: 
      - name: UAA design doc
        url: https://asdfasdf
      - name: Some other doc
        url: https://boobarbazbat
    governors:
      - name: UAA configuration
        url: https://pathtogitrepohead
      - name: Live test results
        url: https://dashboardwithupdatedtestresults
    satisfies:
      - standard: NIST-800-53:C-2
      - standard: PCI:Regulation6
```

## Standards Documentation
```yaml
# nist-800-53.yaml
standards:
  C-2:
    name: User Access
    description: There is an affordance for managing access by...

# PCI.yaml
standards:
  Regulation-6:
    name: User Access PCI
    description: There is an affordance for managing access by...
```

## Certifications 
Empty yaml for creating certification documentation. Serve as a template for combining controls and standards yamls. 

```yaml
# Fisma.yaml
standards:
  nist-800-53:
    C-2:
    C-3:
  PCI:
    6:
```

## Yaml output
Centralized yaml for a specific certification, can be used to render matrix.csv, gitbook.md, ssp.docx... This is were we will be able to see if any pieces are missing. 
```yaml
# FISMA_Project.yaml
standards:
  nist-800-53:
    C-2:
      name: User Access
      description: There is an affordance for managing access by...
      justifications:
        - name: Cloud Foundry User Authentication and Authorization (UAA)
          narrative: This is a separate component that blahblahblah. It segments access by blahblahblah.
          references: 
            - name: UAA design doc
              url: https://asdfasdf
            - name: Some other doc
              url: https://boobarbazbat
          governors:
            - name: UAA configuration
              url: https://pathtogitrepohead
            - name: Live test results
              url: https://dashboardwithupdatedtestresults
    C-3:
      a:
  PCI:
    Regulation-6:
      name: User Access PCI
      description: There is an affordance for managing access by...
      justifications:
        - name: Cloud Foundry User Authentication and Authorization (UAA)
          narrative: This is a separate component that blahblahblah. It segments access by blahblahblah.
          references: 
            - name: UAA design doc
              url: https://asdfasdf
            - name: Some other doc
              url: https://boobarbazbat
          governors:
            - name: UAA configuration
              url: https://pathtogitrepohead
            - name: Live test results
              url: https://dashboardwithupdatedtestresults
```

### CODE REVIEW

**Comment by joshuamckenty** [comment]
So... when I see a lot of discussion of merging yaml files together, it makes me think of spiff. (https://github.com/cloudfoundry-incubator/spiff) While fairly BOSH-centric, there don't seem to be a lot of tools in this space yet. Thoughts?

**Comment by ramirezg** [comment]
@joshuamckenty This is a really interesting library. I'll try it out. My main concern is that people will have to learn the syntax to modify the yamls. 

I'm thinking of moving away from Javascript to Go or Python for this task to make testing, validations, and error checking easier...

**Comment by joshuamckenty** [comment]
Would love to hear what @Amit-PivotalLabs thinks on the syntax concerns.

**Comment by Amit-PivotalLabs** [comment]
We're planning to move away from spiff for several reasons:

1. It's too flexible, and it's too easy to start using it in very complex ways.  What I'd foresee happening is not that your developers will have to invest time learning the spiff syntax, but learning whatever complex patterns other developers have created around using spiff and managing templates.  This is the place we're currently in.

2. It has some annoying quirks, e.g. it rearranges hash keys in alphabetical order, so if you have something like:

```
things:
  - name: first_thing
    data: some data
    other_data: more data
    additional_data: even more data
  - name: second_thing
    data: foo
    other_data: bar
    additional_data: baz
```

```
things:
  - additional_data: even more data
    data: some data
    name: first_thing
    other_data: more data    
  - additional_data: baz
    data: foo
    name: second_thing
    other_data: bar    
```

For a human, you want `name:` to be the first key, but with spiff it won't be.

Another annoying quirk is that in order to bring data from one file into another, you need to tell spiff to essentially copy the second file into the top level of the first file, and then you can pick off values from that data and merge it into the appropriate slots in the first file.  What results is a YAML file with the stuff you want, plus all the intermediate data you had to copy beside it.  We often use a top-level "mask" template just to filter out the noise, which is just working around a spiff quirk.

3. While on the one hand it is too flexible and can do too much, for BOSH purposes we often find it can't do enough.  I won't get into the details, but I foresee something like that happening here as well.  You want logic like: for each standard, and for each regulation under that standard, find the controls which satisfy that regulation, and include the name, narrative, references, and governors under the justifications section.  The "find the controls which satisfy that regulation" logic is not something I imagine spiff is capable of.

Without knowing the full context of what you folks are trying to achieve, I'd imagine building/testing the simplest possible thing that meets the requirements for the logic you'd want to have for your YAML merging would be the way to go, vs. taking the easy off-the-shelf spiff solution which might end up being ill-suited.

**Comment by dlapiduz** [comment]
Thanks @Amit-PivotalLabs I thought this was the case. We should try to keep this repo simple and use some sort of custom script to merge the files in some "sane" way.

**Comment by dlapiduz** [comment]
@NoahKunin @joshuamckenty we are moving on the component level model here: https://github.com/18F/control-masonry/pull/7. Please take a look if you don't mind.

**Pull request closed without merging**
